import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Admin | REX SHOP',
  description: 'Generated by create next app',
}

const AdminHeader = () => {
  return (
    <div className="flex">

    </div>
      
  );
};

export default AdminHeader;
