
import productApiRequest from "@/apiRequests/product";
import { Metadata } from "next";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import Link from "next/link";
import DeleteProduct from "./_components/delete-product";
export const metadata: Metadata = {
  title: 'Quản lý sản phẩm | REX SHOP',
  description: 'Generated by create next app',
}

export default async function ProductAdmin() {
  const { payload } = await productApiRequest.getList();
  const productList = payload.data;
  // Sét giá VND
  function formatVND(value: number | bigint) {
    return new Intl.NumberFormat('vi-VN', {
      style: 'currency',
      currency: 'VND',
      maximumFractionDigits: 0, // Omitting decimal values for VND as they are generally not used
    }).format(value);
  }
  return (
    <div className="container">
      <h2 className="text-2xl font-bold mb-6">Quản lý sản phẩm</h2>
        <Link href={"/admin/products/add"}>
          <Button variant={"destructive"}>Thêm sản phẩm</Button>
        </Link>

      <div className="grid gap-10 grid-cols-3">
        <div className="col-span-4">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Sản phẩm</TableHead>
                <TableHead>Số lượng</TableHead>
                <TableHead className="text-center">Giá</TableHead>
                <TableHead className="text-center">Loại</TableHead>
                <TableHead className="text-center">Thao tác</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
            {productList.map((product) => (
                  <TableRow key={product.id}>
                    <TableCell className="font-medium w-[65%]">
                      <div className="flex space-x-4">
                        <Image
                          src={product.img}
                          alt={product.name}
                          width={120}
                          height={60}
                          className="w-24 h-24 rounded-lg"
                        />
                        <div>
                          <h3 className="text-lg">{product.name}</h3>
                          <p className="text-xs font-light line-clamp-2 w-[80%]">
                            {product.description}
                          </p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>{product.quantity}</TableCell>
                    <TableCell className="text-center">
                    {formatVND(product.price)}
                    </TableCell>
                    <TableCell className="text-center">
                      {product.categoryName}
                    </TableCell>
                    <TableCell>
                     <div className="space-x-2 text-center flex">
                       <Link href={`/admin/products/${product.id}/edit`} >
                         <Button variant={"outline"} >Edit</Button>
                       </Link>
                       <DeleteProduct product={product} />
                     </div>
                    </TableCell>
                  </TableRow>
               ))}
            </TableBody>
          </Table>
        </div>

      </div>
      
    </div>
  );
}
