import productApiRequest from "@/apiRequests/product";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { cookies } from "next/headers";
import ProductBreadcrumb from "@/components/products/products-breadcrum";
import { Metadata } from "next";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AccountResType } from "@/schemaValidations/account.schema";

export const metadata: Metadata = {
  title: 'User',
  description: 'Generated by create next app',
}
export default async function ProductListPage({
    user,
}: {
  user: AccountResType["data"] | null;
}) {
  const { payload } = await productApiRequest.getList();
  const userList = payload.data;

  return (
    <div className="container">
      <h2 className="text-2xl py-4">Danh sách người dùng</h2>   
            <div className="grid gap-10 grid-cols-3">
            <div className="col-span-4">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Tên</TableHead>
                    <TableHead>Email</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                {userList.map((user, index) => (
                      <TableRow key={index}>
                        <TableCell className="font-medium">
                          <div className="flex space-x-4">
                            {user.name}
                          </div>
                        </TableCell>
                        <TableCell>1</TableCell>
                        <TableCell className="text-right">
                            {/* {user.email} */}
                        </TableCell>
                      </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
    </div>
  );
}
