
import HeroBanner from '@/components/banner'
import HomeContainer from '@/components/home-container'
import ProductNew from '@/components/layout/product-new'
import { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'REX SHOP',
  description: 'Generated by create next app',
}

const isAuth = false
export default function Home() {
  // if (!isAuth) {
  //   redirect('/login')
  // }
  return (
    <main>
        <HeroBanner />
        <HomeContainer />
        <ProductNew />
    </main>
  )
}